[K8sDnsNameResolver] Fix Netty panic logging on JVM shutdown
Removes this erroneous log message on JVM shutdown:
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!

Why it was logged:
- it seems to happen when LookupSession.lookupAsync tries to establish a new DNS server connection after the JVM shutdown has already started (it could happen because JVM shutdown hooks are executed in unpredictable order)
- under the hood that function tries to register a JVM shutdown hook to clean up NIO resources
registering a shutdown hook during the shutdown sequence results in java.lang.IllegalStateException: Shutdown in progress
- this exception is not reported as a failure case in LookupSession.lookupAsync result completion stage but is thrown directly on the method call
- the code inside the resolver doesn't handle such direct exception gracefully, which causes it to propagate to Netty internals, resulting in a scary "Panic! This is a bug!" log message written to JUL by Netty internals

The fix:
- catch and handle the "error on JVM shutdown" case
- reduce the log level for such errors below INFO
- additionally, the resolver shutdown logic was hardened for all the cases where currently running resolution is in a race with the shutdown